In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
     'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3058, 3929, 9057, 9411],
 [3058, 3929, 9057, 1847],
 [3058, 3432, 9057, 2769],
 [3376, 994, 6205, 6827, 3961],
 [3376, 994, 6205, 6827, 3502],
 [2597, 3058, 501, 9057, 441],
 [7132, 7135, 697, 6827]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3058 3929 9057 9411]
 [   0    0    0    0 3058 3929 9057 1847]
 [   0    0    0    0 3058 3432 9057 2769]
 [   0    0    0 3376  994 6205 6827 3961]
 [   0    0    0 3376  994 6205 6827 3502]
 [   0    0    0 2597 3058  501 9057  441]
 [   0    0    0    0 7132 7135  697 6827]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 76ms/step


array([[[ 0.04534096, -0.00019671, -0.04776704,  0.03439622,
         -0.01443968,  0.03945999,  0.03392464, -0.01891757,
          0.03696315,  0.0147281 ],
        [ 0.04534096, -0.00019671, -0.04776704,  0.03439622,
         -0.01443968,  0.03945999,  0.03392464, -0.01891757,
          0.03696315,  0.0147281 ],
        [ 0.04534096, -0.00019671, -0.04776704,  0.03439622,
         -0.01443968,  0.03945999,  0.03392464, -0.01891757,
          0.03696315,  0.0147281 ],
        [ 0.04534096, -0.00019671, -0.04776704,  0.03439622,
         -0.01443968,  0.03945999,  0.03392464, -0.01891757,
          0.03696315,  0.0147281 ],
        [ 0.02648071, -0.02320843, -0.02228068,  0.02883637,
          0.0337628 ,  0.04625387,  0.01483274, -0.00662575,
          0.00618368, -0.00982821],
        [-0.0197522 ,  0.04239665, -0.02034668, -0.03257956,
          0.01913637, -0.03920561,  0.0264662 , -0.03629054,
          0.04979613, -0.0381529 ],
        [-0.01601905, -0.02599808,  0.02341895,  0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 3058, 3929, 9057, 9411])

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 48ms/step


array([[ 0.04534096, -0.00019671, -0.04776704,  0.03439622, -0.01443968,
         0.03945999,  0.03392464, -0.01891757,  0.03696315,  0.0147281 ],
       [ 0.04534096, -0.00019671, -0.04776704,  0.03439622, -0.01443968,
         0.03945999,  0.03392464, -0.01891757,  0.03696315,  0.0147281 ],
       [ 0.04534096, -0.00019671, -0.04776704,  0.03439622, -0.01443968,
         0.03945999,  0.03392464, -0.01891757,  0.03696315,  0.0147281 ],
       [ 0.04534096, -0.00019671, -0.04776704,  0.03439622, -0.01443968,
         0.03945999,  0.03392464, -0.01891757,  0.03696315,  0.0147281 ],
       [ 0.02648071, -0.02320843, -0.02228068,  0.02883637,  0.0337628 ,
         0.04625387,  0.01483274, -0.00662575,  0.00618368, -0.00982821],
       [-0.0197522 ,  0.04239665, -0.02034668, -0.03257956,  0.01913637,
        -0.03920561,  0.0264662 , -0.03629054,  0.04979613, -0.0381529 ],
       [-0.01601905, -0.02599808,  0.02341895,  0.0198077 , -0.01080617,
        -0.02666512,  0.00736555,  0.00559258